### ISSUE TITLE
[Bug] Vault API EconomyResponse returns old balance for withdraws and deposits

### ISSUE THREAD

**Issue by Rumsfield** [ItsWagPvP/EconomyPlus#1]
Other plugins which use EconomyPlus as an economy provider can register it as an economy provider and use [Vault API](http://milkbowl.github.io/VaultAPI/) methods. Calling [withdrawPlayer(org.bukkit.OfflinePlayer player, double amount)](http://milkbowl.github.io/VaultAPI/net/milkbowl/vault/economy/Economy.html#withdrawPlayer-org.bukkit.OfflinePlayer-double-) returns an EconomyResponse object, which includes a [balance](http://milkbowl.github.io/VaultAPI/net/milkbowl/vault/economy/EconomyResponse.html#balance) field that's described as **"New balance of account"**

The current implementation of withdrawPlayer() in EconomyPlus returns the old balance of the player, before the account balance was modified. To match Vault API expected behavior, balance modifier methods should return the new amount.

**Comment by ItsWagPvP** [comment]
Solved with #2
