### ISSUE TITLE
[BUG] Datra inconsistency Using /bank

### ISSUE THREAD

**Issue by Aom92** [ItsWagPvP/EconomyPlus#14]
**Describe the bug**

Allowing players to use /bank causes money to be duplicated. 

**To Reproduce**
1. Deposit any non 10 multiple number into the bank
2. Check player Balance, money did not quet retrieved from his balance but money was added intro bank
3. Withdraw money from player, player has know 2x his original amount of moneys.

**Expected behavior**
Money deposited into the bank should decrease accordingly player's balance.

**Comment by ItsWagPvP** [comment]
fixed in V3.0
