### ISSUE TITLE
[BUG] Databases timing problem

### ISSUE THREAD

**Issue by t4gh5yj6j** [ItsWagPvP/EconomyPlus#20]
![image](https://user-images.githubusercontent.com/67204462/148131839-be8c12a3-ff6a-43dc-86f7-1a16e6a12c46.png)

I have this problem, but in the config i set "H2"

**Comment by ItsWagPvP** [comment]
can you paste /ep debug?

**Comment by t4gh5yj6j** [comment]
![image](https://user-images.githubusercontent.com/67204462/148134617-b9381f6c-6fa1-4138-8089-c3196b1f2f98.png)
