### ISSUE TITLE
[BUG] /ep hologram permission check does not work

### ISSUE THREAD

**Issue by BadWolf-i** [ItsWagPvP/EconomyPlus#36]
Players whichout rermissions can do /ep hologram
Is missing return after permisions check 
[https://github.com/ItsWagPvP/EconomyPlus/blob/master/src/main/java/me/itswagpvp/economyplus/commands/Main.java#L102](https://github.com/ItsWagPvP/EconomyPlus/blob/master/src/main/java/me/itswagpvp/economyplus/commands/Main.java#L102)

`                Player p = (Player) sender;

                if (!p.hasPermission("economyplus.hologram")) {
                    p.sendMessage(plugin.getMessage("NoPerms"));
// mising return
                }
`

**Comment by ItsWagPvP** [comment]
this will be fixed in the next update, thanks :)
