### ISSUE TITLE
[BUG] Spigot Download Not Working

### ISSUE THREAD

**Issue by Baezor1** [ItsWagPvP/EconomyPlus#37]
**Describe the bug**
The download link for the plugin on spigot is broken.

**To Reproduce**
1. Go to the [Spigot Page](https://www.spigotmc.org/resources/economyplus.92975/) and attempt to download the latest version.

**Expected behavior**
A download should occur, but doesn't.

**Screenshots**
None needed.

**Additional context**
None needed.

**Comment by ItsWagPvP** [comment]
I've tried it now and it works (?)

**Comment by Baezor1** [comment]
![Screen Shot 2022-08-01 at 10 26 27 AM](https://user-images.githubusercontent.com/64096464/182184358-05c5bd7f-0374-4bc0-9a75-8d8c6e1606c8.png)
I'm not the only one with this issue. Someone else was also able to replicate this.

**Comment by Baezor1** [comment]
<img width="394" alt="ping" src="https://user-images.githubusercontent.com/64096464/182185361-77b60fa0-d688-418b-a934-ac15ff5a61c9.png">

**Comment by Baezor1** [comment]
Since the download link was updated to be hosted on Spigot, ill go ahead and close this ticket.
