### ISSUE TITLE
Extra permissions

### ISSUE THREAD

**Issue by SykoUSS** [ItsWagPvP/EconomyPlus#49]
**Describe the solution you'd like**
Permissions for all commands

**Describe alternatives you've considered**
Permissions for /bank withdraw/deposit

**Additional context**
Our server is set up like an mmo where players need to go to certain locations to access banks, shops, etc. 
We've been looking for a replacement eco plugin and this has been the closest fit, if not for the one command missing perms

**Comment by jakepronger** [comment]
Hey, Thank you for the enhancement I will have a look at this and see If I can add this into the next update.
