### ISSUE TITLE
4.6 Interest can not be disabled

### ISSUE THREAD

**Issue by SykoUSS** [ItsWagPvP/EconomyPlus#52]
**Describe the bug**
Config option for interest has no effect

**To Reproduce**
1. set interest to false
2. start server
3. See error

**Expected behavior**
NO interest occurs

**Comment by jakepronger** [comment]
Thank you for the bug report and am working on it now.

**Comment by jakepronger** [comment]
Issue is fixed and will be updated in the 4.6 release soon.
